CNugteren/CLBlast

CHANGELOG
CMakeLists.txt
README.md
external/clBLAS/src/library/blas/generic/common.c
include/clblast.h
include/internal/database.h
include/internal/database/xgemv.h
include/internal/routines/xgemv.h
include/internal/tuning.h
src/clblast.cc
src/database.cc
src/kernels/xgemm.opencl
src/kernels/xgemv.opencl
src/routines/xaxpy.cc
src/routines/xgemv.cc
src/tuning/tuning.cc
src/tuning/xgemv.cc
test/correctness/routines/xgemv.cc
test/correctness/testabc.cc
test/correctness/testabc.h
test/correctness/testaxy.cc
test/correctness/testaxy.h
test/correctness/testxy.cc
test/performance/client.cc
test/performance/client.h
test/performance/graphs/common.r
test/performance/graphs/xgemv.r
test/performance/routines/xgemv.cc
test/wrapper_clblas.h

Added SGEMV/DGEMV/CGEMV/ZGEMV:
- Includes performance and correctness testing
- Includes new Xgemv kernel and tuner
- Tuned parameters for Iris and Tesla K40m

Added GEMV routine

---

CHANGELOG
README.md
include/internal/routine.h
src/clblast.cc
src/kernels/common.opencl
src/kernels/pad.opencl
src/kernels/padtranspose.opencl
src/kernels/xgemv.opencl
src/routine.cc
src/routines/xgemm.cc
src/routines/xgemv.cc
src/tuning/pad.cc
src/tuning/padtranspose.cc
src/tuning/xgemv.cc
test/correctness/routines/xgemm.cc
test/correctness/routines/xgemv.cc
test/correctness/routines/xsymm.cc
test/correctness/testabc.cc
test/correctness/testabc.h
test/correctness/testaxy.h
test/correctness/tester.cc
test/correctness/tester.h

- Added support for complex conjugate transpose
- Added level-3 routines:
CGEMM/ZGEMM
CSYMM/ZSYMM

Added complex conjugate transpose

---

CHANGELOG
README.md
include/internal/routine.h
include/internal/utilities.h
src/utilities.cc
test/correctness/routines/xaxpy.cc
test/correctness/routines/xgemm.cc
test/correctness/routines/xgemv.cc
test/correctness/routines/xsymm.cc
test/correctness/testabc.cc
test/correctness/testabc.h
test/correctness/testaxy.cc
test/correctness/testaxy.h
test/correctness/tester.cc
test/correctness/tester.h
test/correctness/testxy.cc
test/correctness/testxy.h

Improvements with respect to the testing infrastructure:
- Added absolute error checking when relative errors are less meaningful
- Added an option to distinguish between a short smoke test and a full test
- Automatically skip entire tests when the precision is not supported
- More details in the test summaries

Improved testing infrastructure

---

CHANGELOG
CMakeLists.txt
README.md
include/clblast_c.h
samples/sgemm.c
src/clblast_c.cc

Added:
* Plain C header `clblast_c.h`
* Implementation of C API
* New sample: using the C API to run SGEMM

Added a plain C API

---

.appveyor.yml
CMakeLists.txt

Add option to build shared or static library

---

CMakeLists.txt
include/clblast.h
include/clblast_c.h

Missed testing on Windows when sending in #112.

Fixes for static lib compilation on Windows

---

.travis.yml
samples/cache.c
samples/dgemv.c
samples/haxpy.c
samples/sasum.c
samples/sgemm.c
samples/sgemm.cpp
scripts/generator/generator.py
src/clblast.cpp
src/clblast_c.cpp
src/clpp11.hpp
src/routine.cpp
src/routines/common.hpp
src/utilities/clblast_exceptions.hpp
src/utilities/utilities.hpp
test/correctness/tester.cpp
test/correctness/tester.hpp
test/performance/client.hpp

Minor fixes that materialized during plugins system development (relevant PR will follow shortly). See commit messages.

Assorted minor fixes

---

CHANGELOG
CMakeLists.txt
README.md
doc/clblast.md
include/clblast.h
include/clblast_c.h
scripts/generator/generator.py
src/cache.cpp
src/cache.hpp
src/clblast.cpp
src/clblast_c.cpp
src/database/database.cpp
src/database/database.hpp
src/routine.cpp
src/routine.hpp
src/routines/common.hpp
src/routines/level2/xgemv.cpp
test/correctness/misc/override_parameters.cpp

This implements the features request in #130.

API to override tuning parameters

---

.appveyor.yml
src/utilities/utilities.hpp

Two changes:
* Fixes AppVeyor builds due to a change in Khronos repositories
* Fixes MSVC compilation issue

MSVC compilation fixes

---

test/correctness/misc/override_parameters.cpp
test/correctness/testblas.cpp
test/correctness/tester.cpp
test/correctness/tester.hpp

Several minor improvements for Windows systems and MSVC 2013 compatibility.

Windows & MSVC improvements

---

src/routines/level3/xgemm.cpp

Hi Cedric,
this will restore the previous version of the code for direct GEMM in order to fix the issue [https://github.com/CNugteren/CLBlast/issues/179](url)

Restore direct gemm

---

CMakeLists.txt
src/routines/common.cpp
src/routines/common.hpp
src/utilities/utilities.cpp
src/utilities/utilities.hpp
test/correctness/tester.hpp
test/performance/client.hpp
test/routines/common.hpp
test/test_utilities.cpp
test/test_utilities.hpp

Moved some functions around to potentially reduce required compilation time. Also added all the header files to the CMakeLists such that IDEs such as CLion and Visual Studio known that they are part of the project.

Compilation improvements

---

CHANGELOG
CMakeLists.txt
test/diagnostics.cpp

Added a small helper executable to report device info and perform some small device benchmarks.

Diagnostics helper

---

doc/api.md
include/clblast_c.h
scripts/generator/generator.py
src/clblast_c.cpp

- Added C API for getting temp buffer size
- Updated generator.py header & footer lines 
- Update API doc

Added C API for getting GEMM temp buffer size

---

src/tuning/routines/xgemm.cpp

Added an option to run the routine tuner for a single specific GEMM size. Example use:
```
./clblast_tuner_routine_xgemm -m 1024 -n 1024 -k 1024
```
Example output:
```
* Tuning for one specific size: m=1024, n=1024, k=1024
* Testing the in-direct routine
-->     22.02 ms
* Testing the direct routine
-->     45.21 ms
* Writing a total of 2 results to 'clblast_gemm_routine_single_size_32.json'
* Completed tuning process
```
This is not really part of the regular tuning process, but could be used for other use-cases, such as for benchmarking or model building.

Added an option to run the routine tuner for a single specific GEMM size

---

src/routines/common.cpp
src/routines/common.hpp
src/routines/level2/xtrsv.cpp
src/routines/level3/xtrsm.cpp
src/routines/levelx/xinvert.cpp

Added a check to return 'NotImplemented' error code in case of systems with < 16 LWGS for TSRV and TRSM

Apple opencl limitations for TRSV/TRSM now return not-implemented status

---

CMakeLists.txt
src/clpp11.hpp

See issue #301 or the original bug reported on the AMD forums:
https://community.amd.com/message/2869393#comment-2869393

Added workaround for AMD Southern Islands GPU issue

---

CHANGELOG
src/routines/common.hpp
test/correctness/testblas.cpp
test/routines/levelx/xomatcopy.hpp
test/test_utilities.cpp
test/test_utilities.hpp

Fixed an issue with conjugate transpose not being executed in certain cases for a.o. XOMATCOPY.
See #306.

Fixes bug in conjugate transpose not being executed

---

CHANGELOG
CMakeLists.txt
scripts/generator/generator.py
scripts/generator/generator/cpp.py
src/clblast_netlib_c.cpp

Netlib API with optional static OpenCL variables

---

src/clpp11.hpp
src/routines/level2/xtrsv.cpp
src/routines/level2/xtrsv.hpp
src/routines/level3/xtrsm.cpp
src/routines/level3/xtrsm.hpp

Missing events in TRSV and TRSM

---

doc/bindings.md

I've written a wrapper of CLBlast in Julia which can be found [here](https://github.com/JuliaGPU/CLBlast.jl). It is published and available using the Julia package manager.

Add Julia Wrapper

---

CHANGELOG
src/kernel_preprocessor.cpp
src/kernels/level3/xgemm_part1.opencl
src/kernels/level3/xgemm_part2.opencl
src/kernels/level3/xgemm_part3.opencl
src/kernels/level3/xgemm_part4.opencl
src/routines/level3/xgemm.cpp
src/routines/level3/xherk.cpp
src/routines/level3/xsyrk.cpp
src/routines/levelx/xgemmbatched.cpp
src/routines/levelx/xgemmstridedbatched.cpp
src/tuning/kernels/xgemm.hpp
src/utilities/compile.cpp
test/correctness/misc/preprocessor.cpp

Fixed pre-processor issues with the new GEMMK=1 kernel

---

CHANGELOG
src/kernels/level1/xaxpy.opencl

Fixed a bug in the XaxpyFaster kernel for specific parameters

---

src/kernels/levelx/col2im.opencl
src/routines/levelx/xcol2im.cpp
src/utilities/utilities.cpp
src/utilities/utilities.hpp
test/routines/levelx/xcol2im.hpp

Related to #270 
This branch adds `col2im` function.
I have some questions.
1. In the CPU implementation, I clear `buffers_host` using a for-loop. Is there a better method for clearing buffer?
2. Some errors occur in half-float tests in my environment. How to fix it? It may be a floating point precision error.
```
::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::                                                                           
XXXX::::XXXX::::X:X:::::X:X:::::::::::::XXXX::::X:X:::::XXXX::::                                                                          
::XXXXXX::::::::XXXXXXXX::::::::XX::XXXX::::::::XXXXXXXX::::::::                                                                           
:XX::XXXX::X::::XXX::X:XX:X:::::XX:::X::X:X:::::XXXXXX::X:X::::: …
```

Add col2im function

---

src/clpp11.hpp
src/kernels/level3/xgemm_part1.opencl
src/routine.cpp
src/utilities/compile.cpp
src/utilities/utilities.cpp
src/utilities/utilities.hpp

intel shuffle extension fix

---

CHANGELOG
src/kernels/level1/xamax.opencl

Fixed a bug in the absolute-min index kernel

---

CHANGELOG
src/tuning/kernels/copy_fast.cpp
src/tuning/kernels/copy_pad.cpp
src/tuning/kernels/invert.cpp
src/tuning/kernels/transpose_fast.cpp
src/tuning/kernels/transpose_pad.cpp
src/tuning/kernels/xaxpy.cpp
src/tuning/kernels/xconvgemm.cpp
src/tuning/kernels/xdot.cpp
src/tuning/kernels/xgemm.cpp
src/tuning/kernels/xgemm_direct.cpp
src/tuning/kernels/xgemv.cpp
src/tuning/kernels/xger.cpp
src/tuning/routines/xgemm.cpp
src/tuning/routines/xtrsv.cpp

Catches all exceptions of the tuners

---

src/tuning/tuning.cpp

Move queue creation out of the tuner loop

---

CHANGELOG
scripts/generator/generator/pyclblast.py
scripts/generator/generator/routine.py
src/pyclblast/samples/saxpybatched.py
src/pyclblast/setup.py
src/pyclblast/src/pyclblast.pyx

PyCLBlast: add missing batched routines

---

scripts/benchmark/utils.py

See https://github.com/CNugteren/CLBlast/issues/395

Fix a Python 3 bug in the benchmark script

---

src/pyclblast/setup.py

Add library dir on Linux for pyclblast

---

src/pyclblast/setup.py

Fix Windows paths in pyclblast

---

src/tuning/kernels/xgemm.hpp
test/routines/level3/xgemm.hpp
test/routines/level3/xsymm.hpp
test/routines/level3/xsyrk.hpp
test/routines/level3/xtrmm.hpp
test/routines/level3/xtrsm.hpp
test/routines/levelx/xgemmbatched.hpp
test/routines/levelx/xgemmstridedbatched.hpp

Set the correct flop count for xgemm (especially cgemm and zgemm).
Related to #415

set the correct flop count for xgemm

---

README.md

Removed old ArrayFire test machines and add new ones

Remove old test machines and add new ones

---

.appveyor.yml
.gitignore
.travis.yml
CHANGELOG
CMakeLists.txt
include/clblast.h
include/clblast_c.h
samples/dtrsm.cpp
samples/sgemm.cpp
samples/sgemm_batched.cpp
samples/tuning_api.cpp
src/pyclblast/README.md
src/pyclblast/setup.py

Part of https://github.com/CNugteren/CLBlast/issues/441

Update to version 1.5.3

---

CHANGELOG
scripts/benchmark/plot.py

This closes https://github.com/CNugteren/CLBlast/issues/443 and https://github.com/CNugteren/CLBlast/issues/445

Fix two small issues in the plotting script

---

CHANGELOG
src/clpp11.hpp

See https://github.com/CNugteren/CLBlast/issues/450#issuecomment-1532437521

Fixes an issue under Android when the driver was already unloaded

---

.github/workflows/build_and_test.yml
test/correctness/testblas.hpp

Attempt to resolve issues in ArrayFire Windows builds, see https://github.com/CNugteren/CLBlast/issues/463#issuecomment-1550994839. Also adds Windows builds to the Github Actions.

Add Windows builds to Github Actions and fix Windows compilation issue

---

.github/workflows/release.yml

This fixes https://github.com/CNugteren/CLBlast/issues/479.

Use NMake for Windows builds

---

.github/workflows/release.yml

Test build succeeded here:
https://github.com/CNugteren/CLBlast/actions/runs/5093773464

Fix folder name of Windows release

---

CHANGELOG
src/kernel_preprocessor.cpp
test/correctness/misc/preprocessor.cpp

This should fix https://github.com/CNugteren/CLBlast/issues/497 and also extend the test to cover the newly fixed situation.

Fix preprocessor and extend test coverage

---

CHANGELOG
CMakeLists.txt

This should fix https://github.com/CNugteren/CLBlast/issues/574.

Fixed compatibility with CMake 4.0

---

doc/tuning.md

This improves the documentation to simplify usage of the tuners by providing a section with details on the common parameters (precision, platform, device, fraction, and threads).

Improved documentation in tuning.md.
