CNugteren/CLBlast

- CHANGELOG
- include/internal/clpp11.h
- include/internal/routine.h
- src/routine.cc
- src/routines/xaxpy.cc
- src/routines/xgemm.cc
- src/routines/xgemv.cc
- src/routines/xsymm.cc
Improved host-code performance by omitting a copy of the `Program` class, containing the OpenCL binary. This leads to performance improvements in case the program is already in the cache (from a previous run).
> Host-code performance

- CHANGELOG
- include/internal/routine.h
- src/routine.cc
- src/routines/level3/xgemm.cc
- src/routines/level3/xher2k.cc
- src/routines/level3/xherk.cc
- src/routines/level3/xsyr2k.cc
- src/routines/level3/xsyrk.cc
- test/performance/graphs/xgemm.r
- test/performance/graphs/xsymm.r
- test/performance/graphs/xsyr2k.r
- test/performance/graphs/xsyrk.r
- test/performance/graphs/xtrmm.r
Added the possibility to bypass pre-processing and/or post-processing kernels for level-3 routines. In case the bypass is used (e.g. no transpose is needed, no padding is needed), the temporary buffer is also not allocated. This improves performance and saves memory in specific scenarios: certain input sizes (multiple of tile-size) and certain transpose/layout configurations.
Also changed the default layout to column-major for the performance graphs and made the 3 triangular-related arguments to the pre/post-processing method optional.
> Bypass pre/post-processing

- test/correctness/routines/level1/xaxpy.cc
- test/correctness/routines/level2/xgemv.cc
- test/correctness/routines/level3/xgemm.cc
- test/correctness/routines/level3/xhemm.cc
- test/correctness/routines/level3/xher2k.cc
- test/correctness/routines/level3/xherk.cc
- test/correctness/routines/level3/xsymm.cc
- test/correctness/routines/level3/xsyr2k.cc
- test/correctness/routines/level3/xsyrk.cc
- test/correctness/routines/level3/xtrmm.cc
- test/correctness/testblas.h
- test/routines/level1/xaxpy.h
- test/routines/level2/xgemv.h
- test/routines/level3/xgemm.h
- test/routines/level3/xhemm.h
- test/routines/level3/xher2k.h
- test/routines/level3/xherk.h
- test/routines/level3/xsymm.h
- test/routines/level3/xsyr2k.h
- test/routines/level3/xsyrk.h
- test/routines/level3/xtrmm.h
Generalised the correct correctness testers of the various routines: they now all share a single function to loop over all relevant options. Behaviour is exactly as before, but code is no longer duplicated and maintainability is increased.
> Refactored the correctness tests

- CHANGELOG
- CMakeLists.txt
- README.md
- include/clblast.h
- include/internal/routines/level2/xgemv.h
- include/internal/routines/level2/xhemv.h
- include/internal/routines/level2/xsymv.h
- src/clblast.cc
- src/kernels/xgemv.opencl
- src/routines/level2/xgemv.cc
- src/routines/level2/xhemv.cc
- src/routines/level2/xsymv.cc
- test/correctness/routines/level2/xhemv.cc
- test/correctness/routines/level2/xsymv.cc
- test/performance/routines/level2/xhemv.cc
- test/performance/routines/level2/xsymv.cc
- test/routines/level2/xhemv.h
- test/routines/level2/xsymv.h
- test/wrapper_clblas.h
Added level-2 routines:
* CHEMV/ZHEMV
* SSYMV/DSYMV
Note: performance is not yet optimal for these routines yet, as they use a pre-processing symmetric-to-regular or hermetian-to-regular kernel and then run the regular GEMV routine. For level-3 routines this works fine, as the overhead is small compared to GEMM. Compared to GEMV it is not: memory bandwidth is scarce.
> Level-2 routines: HEMV and SYMV

- .travis.yml
- README.md
Added an initial `.travis.yml` file to add automatic build testing using Travis CI. For now this tests only the library itself (using GCC 4.8 and Clang 3.4), not the tuners or the performance/correctness tests.
> Added Travis continuous integration

- cmake/Modules/FindCBLAS.cmake
On my Chromebook 2 with Gentoo Linux, the following packages are available:
```
*  sci-libs/blas-reference
Latest version available: 20070226-r4
Latest version installed: 20070226-r4
Size of files: 5208 KiB
Homepage:      http://www.netlib.org/blas/
Description:   Basic Linear Algebra Subprograms F77 reference implementations
License:       BSD
*  sci-libs/cblas-reference
Latest version available: 20030223-r6
Latest version installed: 20030223-r6
Size of files: 194 KiB
Homepage:      http://www.netlib.org/blas/
Description:   C wrapper interface to the F77 reference BLAS implementation
License:       public-domain
```
I have changed the order of the first two library names in `cmake/Modules/FindCBLAS.cmake`:
```
-  NAMES blas cblas mkl blis openblas accelerate
+  NAMES cblas blas mkl blis …
```
> Locate the C BLAS library before the F77 one.

- src/clpp11.hpp
In LocalMemUsage(), there's a first call to clGetKernelWorkGroupInfo to get the "bytes" amount needed to store the result from CL_KERNEL_LOCAL_MEM_SIZE. However, the actual value passed is an "auto result = size_t", which in 32-bit mode is 4 bytes, regardless of the previous return value. The spec describes that it will actually be a cl_ulong which is 8 bytes. To prevent stack corruption, make sure we are in fact passing a cl_ulong.
Also adjust all callers to take the changed type into account.
Fixes issue #72
> Ensure clGetKernelWorkGroupInfo return value fits.

- src/clpp11.hpp
Make sure all out parameters that are passed to functions such as clGetDeviceInfo are large enough to contain the replies.
Also make the default of GetInfo an ulong, though it's worth considering removing the non-templated function here, as it's prone to exactly these kind of errors.
> Make sure the passed types are large enough.

- CMakeLists.txt
- src/clpp11.hpp
- src/database/database.cpp
- src/database/database.hpp
- src/routine.cpp
- src/routine.hpp
- src/routines/common.cpp
- src/routines/common.hpp
- src/routines/level3/xgemm.cpp
This pull request lays a bit of groundwork for adding support and infrastructure for device-specific routines and kernels in CLBlast (as discussed with @psyhtest and exemplified by the [Mali-optimized sgemm routine](http://malideveloper.arm.com/downloads/OpenCL/example_codes/sgemm/)).
Right now these changes facilitate creating "overlay" device-specific libraries (which are linked on top of CLBlast and implement a subset of its routines with same API/ABI). An example of such library can be seen in [intelfx/CLBlast#mali-overlay](https://github.com/intelfx/CLBlast/tree/mali-overlay).
Doing these things is certainly possible without merging this PR ([intelfx/CLBlast#mali-hackish](https://github.com/intelfx/CLBlast/tree/mali-hackish) links with unmodified CLBlast master), but it required me …
> Groundwork for device-specific routines (retry)

- .appveyor.yml
- .travis.yml
- CMakeLists.txt
I believe in pipelining, so here it is, in case you are OK with bumping the CMake dep to 3.2 (see #85).
This allows me to link to CLBlast in Caffe's CMakeLists.txt in ~15 lines of code (see [intelfx/caffe#clblast](https://github.com/intelfx/caffe/tree/clblast)) without writing any boilerplate, with support for non-standard prefixes and all that (so I'm not NOT just adding `-lclblast` to the compiler command line and calling it a day).
> CMakeLists.txt: provide a find_package() config for dependent projects

- src/utilities.cpp
- src/utilities.hpp
- test/correctness/tester.cpp
Support passing environment variables `CLBLAST_PLATFORM` and `CLBLAST_DEVICE` instead of `-platform` and `-device` arguments to test executables.
This is for `ctest`.
(If you remember, earlier I tried to include this commit but it failed unit tests. Now I finally understood the problem.)
> test/correctness: read platform and device from environment

- CMakeLists.txt
The GCC type system does not support attributes (such as `__attribute__((align(N)))` on template arguments. Consequently, each instantiation of a template using a `cl_XXX` type yields a warning:
```
/home/ivan/CK/tools/lib-viennacl-1.7.1-gcc-6.2.0-linux-32/include/viennacl/meta/predicate.hpp:513:39: warning: ignoring attributes on template argument 'cl_double {aka double}' [-Wignored-attributes]
template<> struct is_cl_type<cl_double>{ enum { value = true }; };
```
Strictly speaking, dropping alignment is wrong. However,
* the only way to fix this for real is to apply required attributes directly to each variable declared inside those templates (which is impractical and actually impossible because the alignment values are an implementation detail);
* the alignments currently specified …
> CMakeLists.txt: use -Wno-ignored-attributes to silence unfixable warnings

- CMakeLists.txt
Building the `test_correctness_common` target fails when a reference library header (e.g. `clBLAS.h`) is not in standard paths. This PR adds the header path to the target's include directories.
> Add path to ref library header when building tests.

- CHANGELOG
- include/clblast.h
- scripts/generator/generator.py
- src/clblast.cpp
- src/clpp11.hpp
- src/database/apple_cpu_fallback.hpp
- src/database/database.cpp
- src/database/database.hpp
- src/kernels/common.opencl
- src/routine.cpp
- src/routine.hpp
- src/routines/level1/xaxpy.cpp
- src/routines/level2/xgemv.cpp
- src/utilities/utilities.cpp
This PR provides overrides for Apple's OpenCL CPU implementation. It is a special case compared to all other implementations, as it only supports a 1-dimensional work-group size. In addition, that work-group size is limited to 1024 (in theory) or much lower (kernel resource dependent). Thus, instead of supporting this corner-case in the whole regular flow (starting from the tuner), we provide this file with some manual overrides.
Note: These overrides are to make the Apple CPU work and not crash, they are not in any way optimized parameters. For decent speed don't use Apple's OpenCL CPU implementation in combination with CLBlast.
> Patch to make tests complete on Apple's CPU implementation

- scripts/benchmark/benchmark.py
- scripts/database/database/io.py
Hi Cedric,
I encountered a problem when using Anaconda Python 3 on Windows when recording json files. I had to change "wb" to "w" in 2 files when saving json file (text mode) - it seems to be working with both Python 2 and Python 3. Hope it's correct and of any help ;) ...
Thanks,
Grigori
> changing "wb" to "w" when saving json file (text mode)

- src/cache.hpp
- src/clblast.cpp
- src/routine.cpp
Hi,
I tested this change both with the initial test I wrote for #155 and CLBlast's own tests. All tested but one passed. clblast_test_xtrsm has failed, but it it was failing even before my patch, so I guess it's something unrelated.
```
Test project /home/kpot/sources/clbuild
Start  1: clblast_test_xswap
1/46 Test  #1: clblast_test_xswap .................   Passed    1.68 sec
Start  2: clblast_test_xscal
2/46 Test  #2: clblast_test_xscal .................   Passed    1.00 sec
Start  3: clblast_test_xcopy
3/46 Test  #3: clblast_test_xcopy .................   Passed    1.16 sec
Start  4: clblast_test_xaxpy
4/46 Test  #4: clblast_test_xaxpy .................   Passed    1.69 sec
Start  5: clblast_test_xdot
5/46 Test  #5: clblast_test_xdot ..................   Passed    0.87 sec
Start  6: …
```
> Fixes inability to run GEMM on multiple identical GPUs (issue #155)

- src/database/kernel_selection.hpp
Hi Cedric,
I propose a specific threshold for ARM devices instead of the default one. This threshold seems to  most effective compared to the default one 
Best
Marco
> Add new threshold for ARM

- src/kernels/common.opencl
- src/kernels/level1/level1.opencl
- src/kernels/level2/level2.opencl
- src/kernels/level2/xgemv.opencl
- src/kernels/level2/xgemv_fast.opencl
- src/kernels/level3/copy_pad.opencl
- src/kernels/level3/invert_diagonal_blocks.opencl
- src/kernels/level3/transpose_pad.opencl
- src/kernels/level3/xgemm_direct_part1.opencl
- src/kernels/level3/xgemm_direct_part2.opencl
- src/kernels/level3/xgemm_direct_part3.opencl
- src/kernels/level3/xgemm_part1.opencl
- src/kernels/level3/xgemm_part2.opencl
- src/kernels/level3/xgemm_part3.opencl
- src/routine.cpp
Inline keyword for kernels is not part of the OpenCL 1.1 spec and thus is made optional now. Many compilers do support it, so right now it is enabled for NVIDIA and AMD GPUs. Other compilers will automatically inline anyway, since function calls might not be supported. This fixes an issue with AMD's ROCm and Mesa Clover which both don't understand the inline keyword.
> Made the inline keyword in kernels optional

- CHANGELOG
- src/clblast.cpp
- src/database/database.cpp
- src/database/database.hpp
- src/database/database_structure.hpp
- src/routine.cpp
- test/correctness/misc/override_parameters.cpp
Kernels are now cached based on their routine name and their tuning parameters. This is useful in the future in case of multiple problem-size-specific tuning results, but already helps for users often using the `OverrideParameters` function: existing kernels will still remain cached and new ones will be added for future use.
> Preparation for size specific parameters

- CHANGELOG
- src/clblast.cpp
- src/kernels/level3/xgemm_part3.opencl
- src/routines/level3/xgemm.cpp
- src/tuning/kernels/xgemm.cpp
- test/correctness/misc/override_parameters.cpp
- test/correctness/routines/level3/xgemm.cpp
- test/performance/routines/level3/xgemm.cpp
- test/routines/level3/xgemm.hpp
Three changes actually:
* Allow OverrideParameters function to work before a kernel was first used
* GEMM tests now test both the in-direct and the direct kernels separately
* Gemm in-direct implementation now uses only 1 larger instead of max 3 optional temporary buffers
The last point (main purpose of this PR) was tested on NVIDIA GPUs with mixed benefits: sometimes the malloc is really fast for some unknown reason. But overall this should be a better approach: 1 malloc maximum instead of a maximum of 3.
For the second change: this could identify new bugs in the code, so if tests fail after this PR, then that could be the source.
> Single temporary GEMM buffer

- src/cache.hpp
- src/clblast.cpp
- src/clpp11.hpp
- src/routine.cpp
- src/routine.hpp
- src/utilities/clblast_exceptions.cpp
- src/utilities/utilities.cpp
- src/utilities/utilities.hpp
- test/diagnostics.cpp
- test/test_utilities.cpp
- test/test_utilities.hpp
Some preparations for a possible extension to add a CUDA API to CLBlast. This PR moves some OpenCL-specific things to `clpp11.h`, where they should have been in the first place. This updates `clpp11.h` also to version 9.0, to be in sync with [the latest `cupp11.h`](https://github.com/CNugteren/CLCudaAPI/blob/master/include/cupp11.h).
> Cuda API preparation

- CMakeLists.txt
- clblast.pc.in
The GNUInstallDirs module [1] provides variables that match the install directories for GNU Software and allows users to override them. Without hardcoding paths packagers can choose library paths according to distribution policies (i.e. lib, lib64, lib<arch>, ...).
[1] https://cmake.org/cmake/help/v3.0/module/GNUInstallDirs.html
> Use GNUInstallDirs to determine install paths

- CHANGELOG
- src/utilities/utilities.cpp
- src/utilities/utilities.hpp
- test/performance/client.cpp
- test/test_utilities.cpp
- test/test_utilities.hpp
This is for #210: overriding parameters in the performance clients directly by specifying a list of JSON files with tuner results.
> Override params in clients from tuner JSON

- CHANGELOG
- CMakeLists.txt
- include/clblast.h
- include/clblast_cuda.h
- scripts/generator/generator.py
- src/api_common.cpp
- src/database/database.hpp
- test/correctness/misc/override_parameters.cpp
- test/correctness/misc/retrieve_parameters.cpp
New API to retrieve tuning parameters:
```
StatusCode PUBLIC_API RetrieveParameters(const cl_device_id device, const std::string &kernel_name,
const Precision precision,
std::unordered_map<std::string,size_t> &parameters);
```
Usable as follows:
```
auto parameters = std::unordered_map<std::string,size_t>();
const auto status = clblast::RetrieveParameters(device, "Xgemm", clblast::Precision::kSingle, parameters);
if (status != clblast::StatusCode::kSuccess) { return; } // handle errors here
std::cout << parameters["NWG"] << std::endl;
```
The above would retrieve the parameters `"KWG", "KWI", "MDIMA", "MDIMC", "MWG", "NDIMB", "NDIMC", "NWG", "SA", "SB", "STRM", "STRN", "VWM", "VWN"` for the `Xgemm` routine for a particular device/precision.
> Retrieve tuning parameters

- CMakeLists.txt
- src/routines/levelx/xgemmbatched.cpp
- src/routines/levelx/xgemmstridedbatched.cpp
- src/tuning/routines/routine_tuner.hpp
- src/tuning/routines/xgemm.cpp
Batched GEMM routines now also use the same tuning parameter to select between direct and in-direct versions. The routine tuner was generalised such that it is easier in the future to separate these 3 uses of the selection parameter. Currently not yet separated.
> Kernel selection for batched GEMM

- doc/clblast.md
- scripts/generator/generator/routine.py
Hi!
Just noticed multiple duplicates in lines describing arguments. Most likely the result of a wrong mass find/replace operation in text editor.
> Fix of multiple duplicates in documentation

- scripts/generator/generator.py
- src/pyclblast/samples/override_parameters.py
- src/pyclblast/samples/sgemm.py
- src/pyclblast/src/pyclblast.pyx
As per #254 
Status:
- cython compiles
- but it gives a segfault when I try to call it with e.g.
```python
pyclblast.override_parameters(ctx, 'gemm', 32, {"KWG": 16, "KWI": 2, "MDIMA": 32, "MDIMC": 8, "MWG": 64, "NDIMB": 8, "NDIMC": 8, "NWG": 64, "PRECISION": 32, "SA": 1, "SB": 1, "STRM": 0, "STRN": 0, "VWM": 1, "VWN": 8})
```
My suspicion is with where I'm providing the `cl_device_id` ... I've got little idea what's going on here (I'm pretty green with C++ and can't even find where that's defined). That, or some nastiness like not converting strings nicely, etc. @CNugteren - any ideas?
Good references:
- https://lists.tiker.net/pipermail/pyopencl/2015-June/001890.html 
- https://lists.tiker.net/pipermail/pyopencl/2015-July/001903.html
> Adding override parameters to pyclblast

- CHANGELOG
- ROADMAP.md
- src/kernels/level3/xgemm_part1.opencl
- src/kernels/level3/xgemm_part3.opencl
- src/utilities/compile.cpp
- src/utilities/utilities.hpp
Added support for Intel's subgroup shuffling extensions, as suggested and discussed in #257. Performance is now roughly the same as Intel's kernel with shuffling on Intel GPUs.
> Intel subgroup shuffling

- CHANGELOG
- src/cache.cpp
- src/cache.hpp
- src/clpp11.hpp
- src/routine.cpp
- src/routine.hpp
- src/routines/common.cpp
- src/routines/common.hpp
- src/utilities/compile.cpp
- src/utilities/compile.hpp
Now stores a `shared_ptr` to the Program class in the cache to make sure the OpenCL program is released only once.
> Better cache behaviour of OpenCL programs

- CHANGELOG
- src/tuning/tuning.cpp
- src/tuning/tuning_api.cpp
- src/utilities/utilities.hpp
- test/correctness/testblas.cpp
- test/routines/level2/xhpr.hpp
- test/routines/level2/xhpr2.hpp
- test/routines/level2/xspr.hpp
- test/routines/level2/xspr2.hpp
The CLBlast tuners and correctness tests now use a 'canary' region following the regular buffer to detect and prevent buffer overflow issues. This is inspired by the work of [clARMOR](https://github.com/ROCm-Developer-Tools/clARMOR) by AMD.
> Canary buffer overflow protection

- CHANGELOG
- CMakeLists.txt
- doc/tuning.md
- src/tuning/routines/xgemm.cpp
- test/test_utilities.cpp
The GEMM routine tuner requires pre-tuned GEMM kernels. This is now automatically picked-up from disk and is no longer a two-stage process:
- The GEMM routine tuner checks for existing relevant JSON tuning files in the current folder. If there are any, they are picked-up and the parameters are set to be used.
- If no relevant GEMM kernel tuning parameters are found on disk, a message is printed to screen to inform the user that it is assumed that those kernels are already pre-tuned for. 
- The routine tuners are now part of the alltuners process. Although they still need to be run at the end, there is no intermediate manual step required.
> Routine tuners read kernel JSON from disk

- src/utilities/utilities.hpp
- test/performance/client.cpp
- test/performance/client.hpp
Added an option in the clients to output timing statistics: minimum, mean, and standard-deviation.
Example regular:
```
$ ./clblast_client_xgemm -cblas 0 -warm_up -runs 30
| <--       CLBlast       --> | <--       clBLAS        --> |
m;        n;        k;   layout;   transA;   transB;      lda;      ldb;      ldc;     offa;     offb;     offc;    alpha;     beta;     ms_1; GFLOPS_1;    GBs_1;     ms_2; GFLOPS_2;    GBs_2
512;      512;      512;      101;      111;      111;      512;      512;      512;        0;        0;        0;     2.00;     2.00;     2.00;    134.1;      2.1;    10.74;     25.0;      0.4
```
Example with more statistics:
```
$ ./clblast_client_xgemm -cblas 0 -warm_up -runs 30 -full_statistics
| <--       CLBlast       --> | <--       clBLAS        --> |
m; …
```
> Runtime statistics in client

- CHANGELOG
- src/clpp11.hpp
This is to avoid segfaults when the OpenCL driver unloads first, known to happen under Windows.
> Disabled calls to clReleaseProgram under Windows

- src/routine.cpp
This was causing a crash for me because the temporary Program destructor called
clReleaseProgram on the cl_program with Program, and then clBuildProgram was
called on the same cl_program (belonging to the Program owned by the
shared_ptr, but it's the same cl_program).
> Eliminate a temporary Program object

- CHANGELOG
- src/tuning/configurations.cpp
- src/tuning/configurations.hpp
- src/tuning/kernels/xgemm.cpp
- src/tuning/tuning.cpp
- src/tuning/tuning_api.cpp
The tuners now check for a valid local thread configuration beforehand. This saves compilation time in case kernels won't run anyway, and prevent potential issues such as #303. Also makes sure more valid configurations are explored during random parameter search.
> Tuners now check for valid local thread size

- src/kernel_preprocessor.cpp
- src/kernels/level3/xgemm_part1.opencl
Fix pre-processor warnings as reported in #322.
> Fixed pre-processor warnings related to the subgroup shuffling

- src/kernels/levelx/col2im.opencl
This branch removes unnecessary qualifiers from `Xcol2im` inline function.
Some environments cannot compile it, and dump the following message: `'const bool' cannot be used as the type of a kernel parameter`
> Remove unnecessary qualifier of inline function

- CHANGELOG
- src/routines/level3/xgemm.cpp
Fixed an issue for unequal MWG and NWG and the new GEMMK == 1 kernel. See #340 for more details.
> Fixed an issue for the GEMMK == 1 kernel

- test/correctness/tester.cpp
- test/performance/client.cpp
- test/routines/levelx/xcol2im.hpp
- test/routines/levelx/xconvgemm.hpp
- test/routines/levelx/xim2col.hpp
This branch fixes test cases of HIM2COL, HCOL2IM, and HCONVGEMM.
The current code does not change the reference `kernel_mode` option.
> Fix half-float+kernel_mode test cases of im2col, col2im, and convgemm

- CHANGELOG
- CMakeLists.txt
- doc/routines.md
- src/kernels/levelx/xconvgemm_part1.opencl
- src/kernels/levelx/xconvgemm_part2.opencl
- src/routines/levelx/xconvgemm.cpp
- src/routines/levelx/xconvgemm.hpp
- src/tuning/kernels/xconvgemm.cpp
- src/tuning/kernels/xconvgemm.hpp
- src/tuning/tuning.cpp
- src/tuning/tuning.hpp
- test/correctness/tester.cpp
- test/performance/client.cpp
- test/routines/levelx/xcol2im.hpp
- test/routines/levelx/xconvgemm.hpp
- test/routines/levelx/xim2col.hpp
Related to #267 
This branch fixes the single kernel version of convgemm function, and enables `ConvGemmMethod::kSingleKernel` option.
It also adds a tuner that works on all parameters without errors.
> Fix single kernel version of convgemm

- scripts/generator/generator.py
- scripts/generator/generator/pyclblast.py
- src/pyclblast/README.md
- src/pyclblast/samples/haxpy.py
- src/pyclblast/setup.py
- src/pyclblast/src/pyclblast.pyx
Added support for PyCLBlast, a float conversion function, and a HAXPY example. Bumped version of PyCLBlast to 1.2.0.
> PyCLBlast half precision support

- src/clpp11.hpp
The `cl_nv_device_attribute_query` extention is not available on the
Apple platform. This caused failures during debug builds at runtime.
> Remove assert for extention not available in macOS

- src/kernels/level1/xhad.opencl
Fix an error in XhadFaster where data would be written beyond the end of zgm.
The kernel loop assumed that there was always enough work for each thread to
process WPT items, but this was not enforced. It's possible to detect the
overflow with the "canary" buffer regions, but for SHAD, kCanarySize must be
~500 (much larger than the normal 127).
This commit may improve the performance of XhadFaster, since the kernel was
performing 2x work in some cases (once over real data, once over garbage).
Courtesy of Codeplay Software Ltd.
> Fix out-of-bounds read/write in XhadFaster

- src/routines/levelx/xgemmbatched.cpp
- src/routines/levelx/xgemmstridedbatched.cpp
- src/utilities/buffer_test.hpp
Same level of guarantees to the previous looped test is given by testing the worst case scenario, only, reducing the TestMatrix call count from the number of batches to one, allowing for much higher batch counts without affecting performance.
> Reduced number of TestMatrix calls for the batched xgemm routines.

- CHANGELOG
- src/tuning/tuning.cpp
See #381:
Fixed a bug in the tuners related to global workgroup size not being a multiple of the local
> Fixed tuners global workgroup size

- CHANGELOG
- include/clblast.h
- include/clblast_c.h
- scripts/generator/generator.py
Added CLBLAST_VERSION_MAJOR/MINOR/PATCH defines in headers to store version numbers. See #385.
> Added version number defines

- CHANGELOG
- src/clpp11.hpp
Fixes #391 
Local tests on a system with multiple NVIDIA GPUs passed. Regular run on a single GPU system also looks good.
> Fix Program::GetIR to handle programs with multiple devices

- scripts/benchmark/benchmark.py
There is no guarantee that all empty strings objects are the same or share object with `""` literal.
> Fix Python SyntaxWarning

- scripts/benchmark/benchmark.py
The intention here was to limit the iteration range to common indexes only.
Fix that.
> Fix a typo in benchmark when running fp 16 vs 32

- scripts/benchmark/plot.py
`plt.subplots` tries to be special, and return array or not-array depending on a number of subplots.
It is not actually helpful, and IMHO bad design.
Make it always `ndarray`.
The `and not type(axes) is np.ndarray`, is just in case matplotlib decides to make their behavior more uniform. For now work around it.
Also, no need for `ndarray.flat` really.
Confirmed to work with existing benchmarks (i.e. rows=2, cols=3), and with single graphs (rows=1, cols=1).
> Allow single graph / subplot on plot

- src/kernel_preprocessor.cpp
- src/tuning/tuning.cpp
- src/tuning/tuning_api.cpp
- test/test_utilities.cpp
While building version 1.5.2 for Fedora, I noticed a number of compiler warnings of this form:
```
/builddir/build/BUILD/CLBlast-1.5.2/src/kernel_preprocessor.cpp:221:19: warning: loop variable 'array_name_map' creates a copy from type 'const std::pair<const std::__cxx11::basic_string<char>, long unsigned int>' [-Wrange-loop-construct]
221 |   for (const auto array_name_map : arrays_to_registers) {  // only if marked to be promoted
|                   ^~~~~~~~~~~~~~
/builddir/build/BUILD/CLBlast-1.5.2/src/kernel_preprocessor.cpp:221:19: note: use reference type to prevent copying
221 |   for (const auto array_name_map : arrays_to_registers) {  // only if marked to be promoted
|                   ^~~~~~~~~~~~~~
|                   &
```
This patch uses references types as indicated to …
> Use reference types to prevent unnecessary copying

- CMakeLists.txt
- include/clblast.h
- include/clblast_c.h
- include/clblast_cuda.h
The CLBlastConfig.cmake file was installed to a directory named
CLBLast (notice second capital l), which can cause issues for CMake's
search path when looking for CLBlast on the system.
This commit also fixes other occurrences of the wrong capitalization,
all of it purely cosmetic (i.e. in comments).
> Correct capitalization typo

- src/tuning/tuning.cpp
Fix issue with printing out-of-bounds local/global sizes for level 1 tuners (xdot and xaxpy). This closes https://github.com/CNugteren/CLBlast/issues/418.
> Fix tuner printing issue

- doc/installation.md
Let the installation documentation reflect the fact that CLBlast is now in Debian and Ubuntu
> Update documentation to reflect CLBlast in Debian & Ubuntu

- src/utilities/android.hpp
While compiling on android with clang 13 (thru Termux), this file causes problem, as clang gives the implementation. causing redef.
In order not to have ambiguous definitions, exclude the functions for other compilers
> android.hpp: custom header guard _clang_

- cmake/Modules/FindMKL.cmake
MKL now stores the iomp5 library in the compiler library directory. This change updates the script to find the libiomp5 in the appropriate mkl directory on Linux and Windows.
I just tried to make a minimal change to the FindMKL script. ArrayFire has a more robust version of this in the ArrayFire repo. You can check it out here: https://github.com/arrayfire/arrayfire/blob/master/CMakeModules/FindMKL.cmake
It may require a more recent version of CMake but I am not sure what that is.
> Add logic to find intel OpenMP on oneMKL.

- src/cupp11.hpp
The function `CopyToAsync` has an optional event argument in the OpenCL version, which is used in CLBlast. This makes the code not compile at all if CUDA (through cupp11.hpp`) is used as backend. This issue was found by a CLBlast user and reported privately by email. This PR should fix that.
> Fix API inconsistency in cupp11.hpp

- CHANGELOG
- src/routines/level2/xtrmv.cpp
This could cause an invalid error 'InvalidValue (-30)' status returned by the clEnqueueCopyBuffer. This should fix https://github.com/CNugteren/CLBlast/issues/456.
> TRMV: Use the minimum x buffer size for copying to a temp buffer

- CHANGELOG
- src/routines/level2/xtbmv.cpp
- src/routines/level2/xtpmv.cpp
- src/routines/level2/xtrsv.cpp
This could cause an invalid error 'InvalidValue (-30)' status returned by the clEnqueueCopyBuffer. This should fix https://github.com/CNugteren/CLBlast/issues/460.
> TBMV/TPMV/TRSV: Use the minimum x buffer size for copying to a temp buffer

- .github/workflows/build_and_test.yml
- .github/workflows/release.yml
This way we can automatically make Linux, macOS and Windows release builds using Github Actions CI instead having to rely on local manual Linux builds and separate AppVeyor Windows builds.
Test release was made here:
https://github.com/CNugteren/CLBlast/actions/runs/5001623492/jobs/8960540379
> Add Github Actions release script

- .github/workflows/build_and_test.yml
- CMakeLists.txt
- cmake/Modules/FindCBLAS.cmake
Previously the Windows CI on Github Actions would not build the tests because no BLAS could be found. This is an attempt to solve that:
* Set CMake CMP0074 policy
* ~~Use MKL instead of OpenBLAS~~
* Use pre-downloade OpenBLAS instead
> Github Actions Windows builds with tests

- .github/workflows/release.yml
This fixes some issues seen in https://github.com/CNugteren/CLBlast/actions/runs/5039209358/jobs/9037203184 for Windows releases:
* The folder name with dots did not work, e.g. "clblast-1.6.0" created a folder named "clblast-1". Therefore the final .7z was empty.
* The build was done in debug mode instead of release mode, see https://stackoverflow.com/questions/19024259/how-to-change-the-build-type-to-release-mode-in-cmake
Fixes tested to work here: https://github.com/CNugteren/CLBlast/actions/runs/5049126014
> Fix issues in Windows release script

- CHANGELOG
- scripts/generator/generator/pyclblast.py
- src/pyclblast/setup.py
- src/pyclblast/src/pyclblast.pyx
Pointers can be negative in ARM, so using `size_t` causes an error like this:
```
$ python haxpy.py
Traceback (most recent call last):
File "/home/yubraj/others/yubrajgithub/CLBlast/src/pyclblast/samples/haxpy.py", line 35, in <module>
pyclblast.axpy(queue, n, clx, cly, alpha=alpha_fp16)
File "src/pyclblast.pyx", line 478, in pyclblast.axpy
OverflowError: can't convert negative value to size_t
```
Fixed by doing `:%s/<size_t>/<ptrdiff_t>/g`. After the patch:
```
$ python haxpy.py
```
Also, `platform` module was not imported in `setup.py`. Fixed that too.
> Fix pointer error in `pyclblast` on ARM

- CHANGELOG
- src/cache.cpp
See https://github.com/CNugteren/CLBlast/issues/486 for more details.
This closes https://github.com/CNugteren/CLBlast/issues/486.
> Fix a multithreading bug related to storing objects in the cache

- .github/workflows/release.yml
Fix: tar -cvf replaced with  tar -cvzf in release.yml
Files were just tar files even though they were labeled as .tar.gz
Referenced in issue #507 
https://github.com/CNugteren/CLBlast/issues/507
[As an aside it is possible for github action to create a release automatically using action-gh-release. Here's how I use it - ]
- name: Create github release
uses: softprops/action-gh-release@v1
with:
fail_on_unmatched_files: True
tag_name: ${{ env.VERSION }}
name: ${{ env.VERSION }}
body_path: ./release.body.txt
files: |
./artifacts/Saint_Helens.dmg/Saint_Helens.dmg
./artifacts/Saint_Helens_install.exe/Saint_Helens_install.exe
./repo/LICENSE
./repo/README.md
More details in 
https://github.com/angrave/shrinkwrap-python/blob/main/.github/workflows/shrinkwrap.yml
> Compress tar files in release.yml action

- test/correctness/misc/preprocessor.cpp
This restores compatibility with -Werror=format-security, and fixes issue #529 .
> Supply formatting string to fprintf

- .github/workflows/build_and_test.yml
Downgrade from macOS 14 runner (with Arm M1) to macOS 13 (with x86). This should make CI work again.
> Downgrade from macOS 14 runner (with Arm M1) to macOS 13 (with x86)

- src/tuning/tuning.cpp
This fixes the bug described in issue #613.
> Added a way to catch when the tuner fraction is too small (less than 1).
